package com.mengka.springboot.dao.domain;

public class SysMapRegionDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_map_region.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_map_region.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_map_region.x
     *
     * @mbg.generated
     */
    private Integer x;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_map_region.y
     *
     * @mbg.generated
     */
    private Integer y;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_map_region.province
     *
     * @mbg.generated
     */
    private String province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_map_region.lat
     *
     * @mbg.generated
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_map_region.lon
     *
     * @mbg.generated
     */
    private String lon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_map_region.level
     *
     * @mbg.generated
     */
    private Integer level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_map_region.city_no
     *
     * @mbg.generated
     */
    private String cityNo;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_map_region.id
     *
     * @return the value of sys_map_region.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_map_region.id
     *
     * @param id the value for sys_map_region.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_map_region.name
     *
     * @return the value of sys_map_region.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_map_region.name
     *
     * @param name the value for sys_map_region.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_map_region.x
     *
     * @return the value of sys_map_region.x
     *
     * @mbg.generated
     */
    public Integer getX() {
        return x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_map_region.x
     *
     * @param x the value for sys_map_region.x
     *
     * @mbg.generated
     */
    public void setX(Integer x) {
        this.x = x;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_map_region.y
     *
     * @return the value of sys_map_region.y
     *
     * @mbg.generated
     */
    public Integer getY() {
        return y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_map_region.y
     *
     * @param y the value for sys_map_region.y
     *
     * @mbg.generated
     */
    public void setY(Integer y) {
        this.y = y;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_map_region.province
     *
     * @return the value of sys_map_region.province
     *
     * @mbg.generated
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_map_region.province
     *
     * @param province the value for sys_map_region.province
     *
     * @mbg.generated
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_map_region.lat
     *
     * @return the value of sys_map_region.lat
     *
     * @mbg.generated
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_map_region.lat
     *
     * @param lat the value for sys_map_region.lat
     *
     * @mbg.generated
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_map_region.lon
     *
     * @return the value of sys_map_region.lon
     *
     * @mbg.generated
     */
    public String getLon() {
        return lon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_map_region.lon
     *
     * @param lon the value for sys_map_region.lon
     *
     * @mbg.generated
     */
    public void setLon(String lon) {
        this.lon = lon == null ? null : lon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_map_region.level
     *
     * @return the value of sys_map_region.level
     *
     * @mbg.generated
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_map_region.level
     *
     * @param level the value for sys_map_region.level
     *
     * @mbg.generated
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_map_region.city_no
     *
     * @return the value of sys_map_region.city_no
     *
     * @mbg.generated
     */
    public String getCityNo() {
        return cityNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_map_region.city_no
     *
     * @param cityNo the value for sys_map_region.city_no
     *
     * @mbg.generated
     */
    public void setCityNo(String cityNo) {
        this.cityNo = cityNo == null ? null : cityNo.trim();
    }
}