spring:
  datasource:
    url: "jdbc:mysql://127.0.0.1:3306/mengka"
    name: "mengka"
    username: "root"
    password: "544027354"
    driver-class-name : "com.mysql.jdbc.Driver"
mybatis:
  config-location: "classpath:mybatis-config.xml"
