package com.mengka.springboot.commons;

import lombok.Data;

@Data
public class CreditApplyDetailDO {

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_apply_detail.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_apply_detail.submitor
     *
     * @mbg.generated
     */
    private String submitor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column credit_apply_detail.status
     *
     * @mbg.generated
     */
    private Integer status;
}
